import JSZip from 'jszip'

// Helper: Converts a Blob to a pure Base64 string (strips the "data:..." prefix)
const blobToBase64 = (blob) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => {
      // reader.result is like "data:application/zip;base64,UEsDB..."
      // We only want the part after the comma
      const splitResult = reader.result.split(',')
      const base64data = reader.result.split(',')[1]
      resolve(base64data)
    }
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

export async function createCellMLDataFragment(cellmlBlob, fileName) {
  const zip = new JSZip()
  const internalName = fileName ? (fileName.endsWith('.cellml') ? fileName : `${fileName}.cellml`) : 'model.cellml'
  zip.file(internalName, cellmlBlob)

  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  })

  return createDataFragment(zipBlob, 'cellml')
}

/**
 * Assembles a minimal COMBINE/OMEX archive — a ZIP containing a manifest,
 * the flattened CellML model, and a SED-ML simulation description — suitable
 * for opening directly in Web OpenCOR.
 *
 * This is intentionally minimal for now: the SED-ML content generated by
 * generateSedmlData() is still a static placeholder rather than being
 * derived from the workspace's actual plot / simulation-settings /
 * parameter-scan configuration (see sedmlExport.js). `simData` is threaded
 * through regardless so that wiring is already in place once
 * generateSedmlData is fleshed out — right now it's simply ignored.
 *
 * @param {object} cellmlData - The flattened CellML model data.
 * @param {object} [simData] - Simulation/plot/parameter-scan config for the SED-ML doc. Currently unused by generateSedmlData.
 * @returns {Promise<Blob>} The .omex archive as a zip Blob.
 */
export async function generateOmexArchive(cellmlData, simData = {}) {
  const sedmlText = generateSedmlData(simData)

  const manifestXml = buildManifestXml([
    { location: 'document.sedml', format: 'http://identifiers.org/combine.specifications/sed-ml', master: true },
    { location: 'model.cellml', format: 'http://identifiers.org/combine.specifications/cellml' },
  ])

  console.log('OMEX archive manifest.xml:\n', manifestXml)
  console.log('OMEX archive model.cellml:\n', cellmlData.finalName)

  const zip = new JSZip()
  zip.file('manifest.xml', manifestXml)
  zip.file('model.cellml', cellmlData.blob)
  zip.file('document.sedml', sedmlText)

  return zip.generateAsync({ type: 'blob' })
}

export async function createDataFragment(zipBlob, subMimeType) {

  const base64String = await blobToBase64(zipBlob)

  return `data:application/x.vnd.zip-${subMimeType}+zip;base64,${base64String}`
}
