import JSZip from 'jszip'

import { generateSedmlData } from './sedmlExport'

/**
 * Builds the COMBINE archive manifest.xml listing every file included in the
 * archive, plus the mandatory self-referencing "." entry for the archive
 * format itself. See the example archive (enterocyte.omex) for the shape
 * this mirrors.
 */
function buildManifestXml(entries) {
  const contentLines = entries
    .map(
      (entry) =>
        `  <content location="${entry.location}" format="${entry.format}"${entry.master ? ' master="true"' : ''}/>`
    )
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<omexManifest xmlns="http://identifiers.org/combine.specifications/omex-manifest">
  <content location="." format="http://identifiers.org/combine.specifications/omex"/>
${contentLines}
</omexManifest>
`
}

/**
 * Assembles a minimal COMBINE/OMEX archive — a ZIP containing a manifest,
 * the flattened CellML model, and a SED-ML simulation description — suitable
 * for opening directly in Web OpenCOR.
 *
 * This is intentionally minimal for now: the SED-ML content generated by
 * generateSedmlData() is still a static placeholder rather than being
 * derived from the workspace's actual plot / simulation-settings /
 * parameter-scan configuration (see sedmlExport.js). `simData` is threaded
 * through regardless so that wiring is already in place once
 * generateSedmlData is fleshed out — right now it's simply ignored.
 *
 * @param {string} cellmlText - Flattened CellML model text (from generateFlattenedModel).
 * @param {object} [simData] - Simulation/plot/parameter-scan config for the SED-ML doc. Currently unused by generateSedmlData.
 * @returns {Promise<Blob>} The .omex archive as a zip Blob.
 */
export async function generateOmexArchive(cellmlText, simData = {}) {
  const sedmlText = generateSedmlData(simData)

  const manifestXml = buildManifestXml([
    { location: 'document.sedml', format: 'http://identifiers.org/combine.specifications/sed-ml', master: true },
    { location: 'model.cellml', format: 'http://identifiers.org/combine.specifications/cellml' },
  ])

  const zip = new JSZip()
  zip.file('manifest.xml', manifestXml)
  zip.file('model.cellml', cellmlText)
  zip.file('document.sedml', sedmlText)

  return zip.generateAsync({ type: 'blob' })
}